### ISSUE TITLE
'listtransactions' command crashes Vault v2.1.1.0

### ISSUE THREAD

**Issue by malafaya** [cryptogenicbonds/CryptoBullion-CBX#34]
In the Debug window, in Console, when I type the command <i>listtransactions</i>, Vault v2.1.1.0 crashes. It happens everytime in my case.
Windows 10 32-bits OS in 1GB Atom netbook.

**Comment by Alex4J** [comment]
Hello,
listtransactions is supposed to be use with a daemon wallet not a Qt Wallet, so it should not work on Qt.
But the crash is not normal at all, i will check it as soon as possible

**Comment by malafaya** [comment]
In that case, consider it low priority. Thanks.

**Comment by Alex4J** [comment]
Option has been disabled on Qt Wallet untill we fix it
