### ISSUE TITLE
Aesthetic only: Windows system tray popup reports "Type: Mined"

### ISSUE THREAD

**Issue by FiniteRed** [cryptogenicbonds/CryptoBullion-CBX#36]
When the wallet stakes the popup that fades in (down near the clock on a Windows machine) 
has the text:

"Type: Mined"

Where as more accurately it should say:
"Type: PoSP"

Or something to that effect :)

**Comment by Alex4J** [comment]
Good idea :)

**Comment by Alex4J** [comment]
Changed for the next version :)
