### ISSUE TITLE
"Interlaced" options

### ISSUE THREAD

**Issue by malafaya** [cryptogenicbonds/CryptoBullion-CBX#38]
In the Settings >> Options window, the Proxy info is separated from its corresponding checkbox (<i>Connect through SOCKS4 proxy</i>) by another option (<i>Disable spending unconfirmed change</i>), making it quite confusing.

As a side note, I tried activating it and in the debug log I see references to <b>SOCKS5</b> proxy (not SOCKS4).

**Comment by Alex4J** [comment]
Good point, i will see if i can move the checkbox :)

**Comment by Alex4J** [comment]
Fixed for the next version
