### ISSUE TITLE
Unconfirmed transactions appear on top after re-downloading blockchain

### ISSUE THREAD

**Issue by malafaya** [cryptogenicbonds/CryptoBullion-CBX#39]
If you move your wallet to another machine and have to download the blockchain again (or bootstrap it), past unconfirmed transactions (rejected by the network) still present in the wallet will be listed on top (see attached 'main' file).
In the Transactions tab, they also appear on top (see attached 'transactions' file), but here at least you can explicitely sort by date. This sorting however will be lost the next time you start Vault.
For the main tab, there is no manual workaround.

![main](https://cloud.githubusercontent.com/assets/11293825/12091543/a5aed3d0-b2ef-11e5-9b63-166a20254041.png)
![transactions](https://cloud.githubusercontent.com/assets/11293825/12091542/a5abf73c-b2ef-11e5-8e77-f92107e3dd2a.png)

**Comment by malafaya** [comment]
P.S.: The command <i>repairwallet</i> does not clear the rejected transactions from the wallet.

**Comment by Alex4J** [comment]
Fixed for the next version, thank you
