### ISSUE TITLE
'custom change address' not receiving change

### ISSUE THREAD

**Issue by malafaya** [cryptogenicbonds/CryptoBullion-CBX#44]
When sending coins, if you select a custom change address, the wallet will still decide to use some other address for the change.

Vault v2.2.0.0 (II) for Windows (of 8 jan 2015 15:12 UTC)

**Comment by Alex4J** [comment]
Hey thank you i will check what happens :)

**Comment by malafaya** [comment]
Any news on this?

**Comment by Alex4J** [comment]
It should work now, it has been fixed in 2.4.0
