### ISSUE TITLE
Colors dificult to read in input control

### ISSUE THREAD

**Issue by malafaya** [cryptogenicbonds/CryptoBullion-CBX#46]
I don't know if you already addressed this so here it goes.
When choosing inputs (advance input control) to send, when in "Tree mode", the lines for the aggregate values for each address are difficult to read, becauseof the grey color on a black background.

**Comment by Alex4J** [comment]
What color do you recommend ? :)

**Comment by malafaya** [comment]
If the background is to be kept black, then white text. Or if you keep the same text color, an almost white background (not totally white so it will be distinguishable from other non-group lines)

**Comment by Alex4J** [comment]
Ok :)
