### ISSUE TITLE
Assertion failed on init

### ISSUE THREAD

**Issue by FiniteRed** [cryptogenicbonds/CryptoBullion-CBX#48]
Found an error this morning when launching the daemon

> Bound to 0.0.0.0:7695
> Loading block index...
> Loading block index...
> Opening LevelDB in /home/pi/.CryptoBullion/txleveldb
> Transaction index version is 70507
> Opened LevelDB successfully
> cryptobulliond: kernel.cpp:392: unsigned int GetStakeModifierChecksum(const CBlockIndex*): Assertion`pindex->pprev || pindex->GetBlockHash() == hashGenesisBlock' failed.

Exits

**Comment by Alex4J** [comment]
It should be fix on next version, of course only if it is the problem i got during some test, but it looks like similar.
