### ISSUE TITLE
Linux GUI launch error (non-fatal, just a bit annoying)

### ISSUE THREAD

**Issue by FiniteRed** [cryptogenicbonds/CryptoBullion-CBX#49]
Linux GUI launch error (non-fatal, just a bit annoying)

./CryptoBullion-qt64 

> QMetaObject::connectSlotsByName: No matching signal for on_buttonConnect_clicked()
> QObject::connect: No such slot CryptobullionGUI::detectShutdown()

**Comment by Alex4J** [comment]
I never run Qt on Linux, so i suppose you pointed a good error, i will try to find it, thanks :)

**Comment by FiniteRed** [comment]
The majority of long term stakers will be running the wallet on Linux I would imagine, might be worth getting a VM setup to make sure everything ports across correctly from the windows build :)

**Comment by Alex4J** [comment]
Oh i spend most of my time on linux (i have Debian in dualboot on my computer) i prefer use it instead of Windows (i hope one day my favorite games could run well on Linux so i don't have to use windows lol).
I just never use UI because i prefer command line :p

**Comment by FiniteRed** [comment]
Hehehe gr8 answer, me too :D
