### ISSUE TITLE
Linux daemon: block timestamp too far in the future

### ISSUE THREAD

**Issue by FiniteRed** [cryptogenicbonds/CryptoBullion-CBX#50]
Block chain sync gets into the following state and can't get out, I have 5+ hours of the below in my debug log file unfortunately with no new blocks received (not currently staking)

ERROR: ProcessBlock() : CheckBlock FAILED
received block abcc46f4e065ef3d51fa
ERROR: CheckBlock() : block timestamp too far in the future
ERROR: ProcessBlock() : CheckBlock FAILED
received block a039587a014124e483ac
ERROR: CheckBlock() : block timestamp too far in the future
ERROR: ProcessBlock() : CheckBlock FAILED
received block 81bc25d82f32b853054c
ERROR: CheckBlock() : block timestamp too far in the future
ERROR: ProcessBlock() : CheckBlock FAILED
received block 7bd03874e39976d18160
ERROR: CheckBlock() : block timestamp too far in the future
ERROR: ProcessBlock() : CheckBlock FAILED

**Comment by Alex4J** [comment]
Wich version do you use ?

**Comment by FiniteRed** [comment]
Daemon mode on the current branch master, so 2.3.0

**Comment by Alex4J** [comment]
Current master branch is 2.3.1 and it is a bit instable, well i have to fix that too i suppose, i will check what could cause that
