### ISSUE TITLE
Wrong transaction dates displayed in specific circumstances

### ISSUE THREAD

**Issue by malafaya** [cryptogenicbonds/CryptoBullion-CBX#51]
This issue is a bit tricky. Let's see if I can explain with my example.
First, I'm using Vault v2.3.1 (official downloadable version, not test version) for Windows.

So, I started Vault and it started synching. I had two receive txs to catchup. While Vault was catching up, I sent some CBX to my wallet which was immediately acknowledged by Vault (which was still synching at that time) and the current timestamp was put in that specific tx, which was still unconfirmed. So far so good.

After some minutes, Vault finally receives the first of the two receive txs block from the "past". Instead of the actual tx/block timestamp, it displays the timestamp of the above unconfirmed tx (that is, some minutes in the past, instead of some hours before). As the second tx/block is received, the same happens: same timestamp as before is displayed for that tx.

In a timeline:

TX1 generated: PoSP in secondary machine
TX2 generated: PoSP in secondary machine
Started Vault in main computer and it starts synching
TX3 made: receive deposit
Before finished synching, Vault ackowledges pending TX3  broadcasted by network and displays it in the Overview (timestamp = current date/time)
Vault received block for TX1: timestamp displayed is same as TX3's timestamp
Vault received block for TX2: timestamp displayed is same as TX3's timestamp

**Comment by Alex4J** [comment]
Did you transfer your wallet.dat from one computer to an other ?

**Comment by malafaya** [comment]
Yes, but that was some time ago.
The two computers are independent regarding wallet.dat and blockchain data.
When this happened I hadn't copied wallet.dat before starting Vault.

**Comment by Alex4J** [comment]
When you copy wallet.dat, you also copy the "stored transaction time".
That's the reason you can have tx time wrong.
Launch your wallet with the option "-rescan" should give to it the right order:
CryptoBullion-Qt.exe -rescan

**Comment by malafaya** [comment]
The copied wallt didn't have those transactions yet. I copied it much before those transactions happened. From the wallet perspective, the transactions were new.
