### ISSUE TITLE
Impossible to launch daemon for same datadir as Cryptobullion-qt.exe

### ISSUE THREAD

**Issue by malafaya** [cryptogenicbonds/CryptoBullion-CBX#52]
I usually use the QT wallet but I would prefer to use the daemon for staking.
But, with the QT wallet closed, when I launch the daemon for the same datadir, I get:

> CryptoBullion: Error initializing database environment D:\Wallets\CryptoBullion!
>  To recover, BACKUP THAT DIRECTORY, then remove everything from it except for wallet.dat.

I already tried with a new wallet and blockchain downloaded using the QT wallet, without success.

**Comment by Alex4J** [comment]
Ok i will check this daemon when i have some times

**Comment by Alex4J** [comment]
The problem has been found, it's because i used a different version of libdb for the daemon and for the Qt Wallet, so wallet.dat is not compatible.
For now only Qt wallet will be realesed for Windows
