### ISSUE TITLE
Sugestion: New splash screen image 

### ISSUE THREAD

**Issue by FiniteRed** [cryptogenicbonds/CryptoBullion-CBX#53]
Hey

Could I offer an alternative 2.3.3 splash screen for consideration:

http://imgur.com/s7VGbpf

The current one looks a little cartoony for my personal tastes + I have added a solid tag line :D

**Comment by elambert2014** [comment]
Very nice, I love it FR, thanks!

**Comment by Alex4J** [comment]
I love it
