### ISSUE TITLE
EXCEPTION: St9bad_alloc     

### ISSUE THREAD

**Issue by FiniteRed** [cryptogenicbonds/CryptoBullion-CBX#54]
Hey

Been running the new wallet for 11 days now (big improvements over previous version :)), but it crashed out about 4 hours ago with the error below unfortunately...

```
ProcessBlock: ACCEPTED
received block fb0a4eeeefd5c95028db
Closed LevelDB successfully
Flushing wallet.dat
Flushed wallet.dat 352ms
Opening LevelDB in /home/finitered/.CryptoBullion/txleveldb
Transaction index version is 70507
Opened LevelDB successfully
SetBestChain: new best=fb0a4eeeefd5c95028db  height=1392428  trust=655622454094839588  date=03/10/16 19:24:38
ProcessBlock: ACCEPTED
Flushing wallet.dat
Flushed wallet.dat 494ms
Flushed 13732 addresses to peers.dat  1164ms


************************
EXCEPTION: St9bad_alloc       
std::bad_alloc       
CryptoBullion in ThreadDumpAddress() 
```

**Comment by Alex4J** [comment]
Yes i have been reported about the bad_alloc issue some times.
I still have to find the reason, maybe delete you peers.dat it looks like to contains too much address, there is definitely a problem with this part of the wallet, i have to find it

**Comment by Alex4J** [comment]
I am running wallet now and this issue never came again.
I guess it is fixed by my last versions
