### ISSUE TITLE
'Could not rename file' occurs every once in a while

### ISSUE THREAD

**Issue by malafaya** [cryptogenicbonds/CryptoBullion-CBX#55]
Sometimes I get this error in the bottom left corner (where the blockchain progress usually appears) in Vault 2.3.3 for Windows (Windows 10, in both x86 and x64)):

----------------
```
EXCEPTION: St13runtime_error init_blockindex(): error opening database environment IO error: C:\******\txleveldb/3313010.dbtmp: Could not rename file.
C:\**********\Cryptobullion-qt.exe in ProcessMessages()

```
----------------

The filename is different each time (block height?).

I've been getting this for some time already and I thought the problem could be in that specific computer. But I now started a **fresh copy** of the blockchain based on the 2016/02/29 bootstrap in another computer and I started getting a few of these occurences while syncing.

I usually have to restart Vault cause it seems to stop but that's not always the case: sometimes it syncs for some more time and crashes a bit later.

**Comment by Alex4J** [comment]
Try to run your Vault with the -reindex command line arguments, startup can take while but it should try to repair the problem.
I will try to figure out what is causing it, many altcoins seems to have the same problem, most probably a problem caused by Bootstrap

**Comment by malafaya** [comment]
It has possiby something to do with the anti-virus (Avast!).
I suspected its influence and disabled real-time scanning of the wallet dirs and sub-dirs.
So far, and it has been some days already, I no longer experienced this issue.

**Comment by Alex4J** [comment]
Avast is a bad antivirus, you have more problem than anything else with it lol.
I highly recommend Bitdefender even it's a paid one lol, thanks for feedback
