### ISSUE TITLE
Daemon mode: ERROR: CheckProofOfStake() error on sync again

### ISSUE THREAD

**Issue by FiniteRed** [cryptogenicbonds/CryptoBullion-CBX#56]
Hi

Just started synchronising the CBX block chain (daemon mode) after 3 weeks of absence and I'm getting block synchronisation failure errors again.

Restarting the daemon seems to fix the issue temporarily until it comes back several hundred blocks later requiring another restart. Ill keep restarting the daemon until its synchronised but there is definitely a bug in there somewhere :s

FR

PS: I'm running the latest version of the code posted here

> SetBestChain: new best=f49517167c92221321d0  height=1448404  trust=1134612034218962758  date=04/23/16 08:24:31
> ProcessBlock: ACCEPTED
> received block 2575554ee80c3da87bd4
> Closed LevelDB successfully
> Opening LevelDB in /home/finitered/.CryptoBullion/txleveldb
> Transaction index version is 70507
> Opened LevelDB successfully
> SetBestChain: new best=2575554ee80c3da87bd4  height=1448405  trust=1134622896688819948  date=04/23/16 08:26:36
> ProcessBlock: ACCEPTED
> Added 178 addresses from 176.156.155.243: 84 tried, 14019 new
> ResendWalletTransactions()
> Added 178 addresses from 176.156.155.243: 84 tried, 14040 new
> Added 83 addresses from 176.156.155.243: 84 tried, 14053 new
> Added time data, samples 3, offset -415 (-6 minutes)
> receive version message: version 60009, blocks=1466848, us=81.129.207.253:57891, them=82.9.77.178:7695, peer=82.9.77.178:7695
> Added time data, samples 4, offset -225 (-3 minutes)
> receive version message: version 60009, blocks=1466850, us=81.129.207.253:35698, them=176.31.13.198:7695, peer=176.31.13.198:7695
> Added time data, samples 5, offset -173 (-2 minutes)
> nTimeOffset = -173  (-2 minutes)
> receive version message: version 60009, blocks=1466852, us=81.129.207.253:44573, them=84.123.198.174:7695, peer=84.123.198.174:7695
> received block cad52a08085ca28431c7
> ERROR: CheckProofOfStake() : INFO: read txPrev failed
> WARNING: ProcessBlock(): check proof-of-stake failed for block cad52a08085ca28431c72691881b91c6d831238b640acf7c740282e032ee3f15
> received block 8deb7cf1e33c7edd6d65
> ERROR: CheckProofOfStake() : INFO: read txPrev failed
> WARNING: ProcessBlock(): check proof-of-stake failed for block 8deb7cf1e33c7edd6d6596433e27cc1ab8ce14375cd7edcfbe83eb8e174145a6
> received block 24102d4d9e80ee6ae8e8
> ERROR: CheckProofOfStake() : INFO: read txPrev failed
> WARNING: ProcessBlock(): check proof-of-stake failed for block 24102d4d9e80ee6ae8e8c05d0417b3bd8c65161a14fc298835614e231a220b2f
> received block dbd44cb1240e4297f0ea
> connection timeout
> ERROR: CheckProofOfStake() : INFO: read txPrev failed
> WARNING: ProcessBlock(): check proof-of-stake failed for block dbd44cb1240e4297f0eacc85af1ef334bc7fc2d8bfb2123afeb422b2c5bf339d
> received block 0fdd28e507fee760144a
> ERROR: CheckProofOfStake() : INFO: read txPrev failed
> WARNING: ProcessBlock(): check proof-of-stake failed for block 0fdd28e507fee760144a320d77eaa445f4cf9438a8dd4fc1740d34e79d8e3d2e
> received block 0e8734279f1c04e8df1e
> ERROR: CheckProofOfStake() : INFO: read txPrev failed
> WARNING: ProcessBlock(): check proof-of-stake failed for block 0e8734279f1c04e8df1e632eef348c663eca851f6f1bf1f3b030fb62bf940d46
> received block f88775b458110a63eae7
> ERROR: CheckProofOfStake() : INFO: read txPrev failed
> WARNING: ProcessBlock(): check proof-of-stake failed for block f88775b458110a63eae79b151c46f5d0065c0d3f1e0e8e03fcd9ec52abff67fb
> received block 9335efa08924e84f47c9
> trying connection 201.213.131.40:7695 lastseen=479.6hrs
> ERROR: CheckProofOfStake() : INFO: read txPrev failed
> WARNING: ProcessBlock(): check proof-of-stake failed for block 9335efa08924e84f47c9be199a4acc38ba63829d25426a368ecf4e67c59f9382
> getblocks -1 to 00000000000000000000 limit 500
> getblocks -1 to 00000000000000000000 limit 500
> getblocks -1 to 00000000000000000000 limit 500
> Added 134 addresses from 84.123.198.174: 84 tried, 14059 new
> Added 167 addresses from 84.123.198.174: 84 tried, 14058 new
> Added 80 addresses from 84.123.198.174: 84 tried, 14061 new
> connection timeout

**Comment by Alex4J** [comment]
Hello,
Thank you for the report, can you try to launch the daemon with "-reindex" parameter
It will take a while to start and sync, but i want to see if this parameter help to fix this issue.
Thank in advance :)

**Comment by FiniteRed** [comment]
sure, re-syncing with -reindex, will report back when its done....

btw, my client crashed out due to memory exhaustion last night (1GB of ram consumed over about 3 days of staking). Started the re-sync process and got the below again:

> Opening LevelDB in /home/finitered/.CryptoBullion/txleveldb
> connection timeout
> Transaction index version is 70507
> Opened LevelDB successfully
> SetBestChain: new best=f24f206acbcedba8f13a  height=1470524  trust=1279431489307803687  date=05/10/16 17:54:35
> ProcessBlock: ACCEPTED
> received block 13c1f64bd7574d775eb8
> Closed LevelDB successfully
> trying connection 177.242.186.94:7695 lastseen=70.2hrs
> Opening LevelDB in /home/finitered/.CryptoBullion/txleveldb
> Transaction index version is 70507
> Opened LevelDB successfully
> SetBestChain: new best=13c1f64bd7574d775eb8  height=1470525  trust=1279434821338328253  date=05/10/16 17:55:03
> ProcessBlock: ACCEPTED
> received block 2f154f6899a04e17744d
> Closed LevelDB successfully
> Opening LevelDB in /home/finitered/.CryptoBullion/txleveldb
> Transaction index version is 70507
> Opened LevelDB successfully
> SetBestChain: new best=2f154f6899a04e17744d  height=1470526  trust=1279438427032161508  date=05/10/16 17:59:27
> ProcessBlock: ACCEPTED
> getblocks 1470394 to 00000000000000000000 limit 500
> getblocks 1470394 to 00000000000000000000 limit 500
> getblocks 1470394 to 00000000000000000000 limit 500
> received block a042268f0fa03e2c68a0
> ERROR: CheckProofOfStake() : INFO: read txPrev failed
> WARNING: ProcessBlock(): check proof-of-stake failed for block a042268f0fa03e2c68a0a8e406e015e4f4a45cd8a555238005b18ed993f3d03d
> getblocks 1470394 to 00000000000000000000 limit 500
> Added time data, samples 7, offset -120 (-2 minutes)
> nTimeOffset = -422  (-7 minutes)
> Moving 46.0.27.144:7695 to tried
> receive version message: version 60009, blocks=1471841, us=81.129.207.253:42115, them=46.0.27.144:7695, peer=46.0.27.144:7695
> getblocks -1 to 00000000000000000000 limit 500
> received block b598e267a29c271b3270
> ERROR: CheckProofOfStake() : INFO: read txPrev failed
> WARNING: ProcessBlock(): check proof-of-stake failed for block b598e267a29c271b32703c9cce10e8e60a9f733f8f4676015d648aa482c9115a
> received block 7555f44df58d6b253683
> ERROR: CheckProofOfStake() : INFO: read txPrev failed
> WARNING: ProcessBlock(): check proof-of-stake failed for block 7555f44df58d6b2536836bfc45ae1f608ffb7f725933255b9098b6dec8640c92
> received block 8b2add2e3aa6b5f34050
> ERROR: CheckProofOfStake() : INFO: read txPrev failed
> WARNING: ProcessBlock(): check proof-of-stake failed for block 8b2add2e3aa6b5f340501e62f1f39acad11fd034395b5cccc7592eda76724f65
> getblocks -1 to 00000000000000000000 limit 500
> received block 0d9f0697aa87986f1ca5
> ERROR: CheckProofOfStake() : INFO: read txPrev failed
> WARNING: ProcessBlock(): check proof-of-stake failed for block 0d9f0697aa87986f1ca52f567779500ca140783e36884281601eec9bcc19b0cd
> received block a7c90988145291608b1d
> ERROR: CheckProofOfStake() : INFO: read txPrev failed
> WARNING: ProcessBlock(): check proof-of-stake failed for block a7c90988145291608b1d1f94b3f7ef8141bdda78e6d29d1cb985177426514f59
> received block 140094534e8f03b64da7

**Comment by Alex4J** [comment]
Hello,
Unfortuntally, I did not write the whole code, when i search for this error i am finding it comes from this line:
https://github.com/cryptogenicbonds/CryptoBullion-CBX/blob/master/src/kernel.cpp#L362
Comment said "previous transaction not in main chain, may occur during initial download"
I suppose it says it could happens when you sync.
When I look closer to your log, i see you received the block at height 1470526 and then the block at height 1471840 (a042268f0fa03e2c68a0a8e406e015e4f4a45cd8a555238005b18ed993f3d03d)
So it looks like your client don't have block between them (that's what i suppose regarding to the issue)
Are you out of sync and downloading the blockchain or is it happens while you are sync ?

**Comment by Alex4J** [comment]
Possible fix found, if you are on Linux you can compile the _Unstable_ branch of the repo (git checkout Unstable && git pull)
Try it, i think it will fix this issue, keep me informed

**Comment by FiniteRed** [comment]
Hey, yes that seems to have fixed it! Syncing correctly now - no more errors on the Unstable branch :)

**Comment by Alex4J** [comment]
Ok i will merge it in master and prepare a release, thanks :)
