### ISSUE TITLE
windows client fails to start

### ISSUE THREAD

**Issue by tashrobinson** [cryptogenicbonds/CryptoBullion-CBX#65]
Installed 2.4.3 windows installer.  
Windows 10

Get this error
![cbxerror](https://cloud.githubusercontent.com/assets/3846965/21270334/30870aea-c384-11e6-95b3-429a6e374898.png)

**Comment by tashrobinson** [comment]
I resolved this by installing the bootstrap file.

**Comment by elambert2014** [comment]
Hi Tash! Long time

Yeah, this error message looks like a corrupted blockchain but sounds like
you have things under control there.

Hope all is well

Happy Holidays!
