### ISSUE TITLE
Building from Source

### ISSUE THREAD

**Issue by natedavis** [cryptogenicbonds/CryptoBullion-CBX#66]
Hello,

I am having problems building this wallet from source. I am trying to build the latest master from today. I am trying to setup a DockerFile that will build a client for me. In that DockerFile, I have the following - I used the doc to read about how to compile for unix.

    git clone https://github.com/cryptogenicbonds/CryptoBullion-CBX.git /opt/cryptobullion
    cd /opt/cryptobullion
    cd /opt/cryptobullion/src/leveldb/ && make libleveldb.a libmemenv.a
    cd /opt/cryptobullion/src/miniupnpc && make && cd ..
    make -f makefile.unix
    cp /opt/cryptobullion/src/cryptobulliond /usr/local/bin/
    rm -rf /opt/cryptobullion

I am building this on Ubuntu 14:04, and I tried to build it also on Ubuntu 16:04. Both give me the following compile error in make: 

```
g++ -c -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -I/opt/cryptobullion/src -I/opt/cryptobullion/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/opt/cryptobullion/src/leveldb/include -DUSE_LEVELDB -I/opt/cryptobullion/src/leveldb/helpers -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -msse2 -MMD -MF obj/main.d -o obj/main.o main.cpp
main.cpp: In member function 'bool CBlock::ConnectBlock(CTxDB&, CBlockIndex*, bool)':
main.cpp:1813:193: error: 'pindpindex' was not declared in this scope
         int64 nCalculatedStakeReward = GetProofOfStakeReward(nCoinAge, (pindex != NULL && pindex->pprev != NULL) ? pindex->pprev->nBits : 0, nTime, (pindex != NULL && pindex->pprev != NULL) ? pindpindex->pprev->nHeight : ((pindex != NULL && pindex->pprev == NULL) ? 1 : 0), (pindex != NULL && pindex->pprev != NULL) ? pindex->pprev->nMoneySupply : 0, nFees);
                                                                                                                                                                                                 ^
main.cpp: At global scope:
main.cpp:4629:13: warning: 'void ThreadCryptobullionMiner(void*)' declared 'static' but never defined [-Wunused-function]
 void static ThreadCryptobullionMiner(void* parg);
             ^
make: *** [obj/main.o] Error 1
```

Any help in getting this to compile would be appreciated! I can get you the full DockerFIle if that would help. Thank you.

**Comment by Alex4J** [comment]
There were an issue in the code, it's now fixed.
Just git pull and you should be ok for compiling now

**Comment by natedavis** [comment]
Thank you so very much for fixing that! It built great, and I have a full node running now. Thanks again.
